local meth_update = GetInteriorAtCoords(598.24040, -423.3888, 17.620)
RefreshInterior(meth_update)
EnableInteriorProp(meth_update, "light_stock")
EnableInteriorProp(meth_update, "meth_app")
EnableInteriorProp(meth_update, "meth_staff_01")
EnableInteriorProp(meth_update, "meth_staff_02")
EnableInteriorProp(meth_update, "meth_update_lab_01")
EnableInteriorProp(meth_update, "meth_update_lab_02")
EnableInteriorProp(meth_update, "meth_update_lab_01_2")
EnableInteriorProp(meth_update, "meth_update_lab_02_2")
EnableInteriorProp(meth_update, "meth_stock")

local meth_update2 = GetInteriorAtCoords(-67.78810, -1291.193, 23.791)
RefreshInterior(meth_update2)
EnableInteriorProp(meth_update2, "light_stock")
EnableInteriorProp(meth_update2, "meth_app")
EnableInteriorProp(meth_update2, "meth_staff_01")
EnableInteriorProp(meth_update2, "meth_staff_02")
EnableInteriorProp(meth_update2, "meth_update_lab_01")
EnableInteriorProp(meth_update2, "meth_update_lab_02")
EnableInteriorProp(meth_update2, "meth_update_lab_01_2")
EnableInteriorProp(meth_update2, "meth_update_lab_02_2")
EnableInteriorProp(meth_update2, "meth_stock")

local meth_update3 = GetInteriorAtCoords(2862.444, 4456.0014, 41.322)
RefreshInterior(meth_update3)
EnableInteriorProp(meth_update3, "light_stock")
EnableInteriorProp(meth_update3, "meth_app")
EnableInteriorProp(meth_update3, "meth_staff_01")
EnableInteriorProp(meth_update3, "meth_staff_02")
EnableInteriorProp(meth_update3, "meth_update_lab_01")
EnableInteriorProp(meth_update3, "meth_update_lab_02")
EnableInteriorProp(meth_update3, "meth_update_lab_01_2")
EnableInteriorProp(meth_update3, "meth_update_lab_02_2")
EnableInteriorProp(meth_update3, "meth_stock")

local meth_update4 = GetInteriorAtCoords(-310.35440000, -1354.14200000, 23.32933000)
RefreshInterior(meth_update4)
EnableInteriorProp(meth_update4, "light_stock")
EnableInteriorProp(meth_update4, "meth_app")
EnableInteriorProp(meth_update4, "meth_staff_01")
EnableInteriorProp(meth_update4, "meth_staff_02")
EnableInteriorProp(meth_update4, "meth_update_lab_01")
EnableInteriorProp(meth_update4, "meth_update_lab_02")
EnableInteriorProp(meth_update4, "meth_update_lab_01_2")
EnableInteriorProp(meth_update4, "meth_update_lab_02_2")
EnableInteriorProp(meth_update4, "meth_stock")

local weed_update = GetInteriorAtCoords(800.09170, -89.15701, 74.917)
RefreshInterior(weed_update)
EnableInteriorProp(weed_update, "weed_app")
EnableInteriorProp(weed_update, "weed_staff_01")
EnableInteriorProp(weed_update, "weed_staff_02")
EnableInteriorProp(weed_update, "weed_update_lamp")
EnableInteriorProp(weed_update, "weed_fan_update")
EnableInteriorProp(weed_update, "weed_stock")
EnableInteriorProp(weed_update, "weed_plant_v3")

local weed_update2 = GetInteriorAtCoords(552.5862, 2684.1770, 35.043)
RefreshInterior(weed_update2)
EnableInteriorProp(weed_update2, "weed_app")
EnableInteriorProp(weed_update2, "weed_staff_01")
EnableInteriorProp(weed_update2, "weed_staff_02")
EnableInteriorProp(weed_update2, "weed_update_lamp")
EnableInteriorProp(weed_update2, "weed_fan_update")
EnableInteriorProp(weed_update2, "weed_stock")
EnableInteriorProp(weed_update2, "weed_plant_v3")

local weed_update3 = GetInteriorAtCoords(-147.7690, 6303.5957, 24.569)
RefreshInterior(weed_update3)
EnableInteriorProp(weed_update3, "weed_app")
EnableInteriorProp(weed_update3, "weed_staff_01")
EnableInteriorProp(weed_update3, "weed_staff_02")
EnableInteriorProp(weed_update3, "weed_update_lamp")
EnableInteriorProp(weed_update3, "weed_fan_update")
EnableInteriorProp(weed_update3, "weed_stock")
EnableInteriorProp(weed_update3, "weed_plant_v3")

local coke = GetInteriorAtCoords(162.10260, -1711.327, 22.207)
RefreshInterior(coke)
EnableInteriorProp(coke, "coke_app")
EnableInteriorProp(coke, "coke_staff_01")
EnableInteriorProp(coke, "coke_staff_02")
EnableInteriorProp(coke, "coke_stock")

local coke2 = GetInteriorAtCoords(-1974.080, -228.9903, 27.864) 
RefreshInterior(coke2)
EnableInteriorProp(coke2, "coke_app")
EnableInteriorProp(coke2, "coke_staff_01")
EnableInteriorProp(coke2, "coke_staff_02")
EnableInteriorProp(coke2, "coke_stock")

local money = GetInteriorAtCoords(937.73070, -1474.606, 23.043)
RefreshInterior(money)
EnableInteriorProp(money, "light_stock")
EnableInteriorProp(money, "money_app")
EnableInteriorProp(money, "money_staff_02")
EnableInteriorProp(money, "money_stock")

local money2 = GetInteriorAtCoords(-41.5310, 6453.3046, 24.329)
RefreshInterior(money2)
EnableInteriorProp(money2, "light_stock")
EnableInteriorProp(money2, "money_app")
EnableInteriorProp(money2, "money_staff_02")
EnableInteriorProp(money2, "money_stock")

local money3 = GetInteriorAtCoords(-1246.520, -1117.353, 0.7893)
RefreshInterior(money3)
EnableInteriorProp(money3, "light_stock")
EnableInteriorProp(money3, "money_app")
EnableInteriorProp(money3, "money_staff_02")
EnableInteriorProp(money3, "money_stock")

local weapon = GetInteriorAtCoords(2536.508, 4118.2700, 31.460)
RefreshInterior(weapon)
EnableInteriorProp(weapon, "light_stock")
EnableInteriorProp(weapon, "weapon_app")
EnableInteriorProp(weapon, "weapon_staff_01")
EnableInteriorProp(weapon, "weapon_stock")

local weapon2 = GetInteriorAtCoords(1397.311, -2092.379, 45.499)
RefreshInterior(weapon2)
EnableInteriorProp(weapon2, "light_stock")
EnableInteriorProp(weapon2, "weapon_app")
EnableInteriorProp(weapon2, "weapon_staff_01")
EnableInteriorProp(weapon2, "weapon_stock")

local weapon3 = GetInteriorAtCoords(436.5493, -1970.364, 17.290)
RefreshInterior(weapon3)
EnableInteriorProp(weapon3, "light_stock")
EnableInteriorProp(weapon3, "weapon_app")
EnableInteriorProp(weapon3, "weapon_staff_01")
EnableInteriorProp(weapon3, "weapon_stock")